### ISSUE TITLE
About Benchmark

### ISSUE THREAD

**Issue by DESEOUMAIGA** [MahmoudAshraf97/ctc-forced-aligner#14]
Hi, thanks for your contribution. It's an amazing job for audio text forced alignment. 

Have you done any evaluation comparisons? What are the performance differences between this method and the MFA or the TorchAudio forced alignment API?

**Comment by MahmoudAshraf97** [comment]
Check [this](https://github.com/lifeiteng/Aligner-SUPERB)

**Comment by TinaChen95** [comment]
Is there any benchmark of speed / real-time factor ?

**Comment by MahmoudAshraf97** [comment]
it should be similar to [facebook/wav2vec2-large-960h](https://huggingface.co/facebook/wav2vec2-large-960h) found [Here](https://huggingface.co/spaces/hf-audio/open_asr_leaderboard)
