### ISSUE TITLE
AssertionError with blank side

### ISSUE THREAD

**Issue by rehandaphedar** [MahmoudAshraf97/ctc-forced-aligner#17]
I'm getting the same error as #16 again. This time, it reads:
```
AssertionError: ا != 
```

I see that the previous error was:
```
AssertionError: ن != ٰ
```
You added ` ٰ` to the normalisation config. I thought of making a similar PR, but this time there is nothing on the other side.

[text.txt](https://github.com/user-attachments/files/16974666/text.txt)
[audio.wav](https://0x0.st/Xxfh.wav)

**Comment by MahmoudAshraf97** [comment]
these errors will continue to appear with arabic, can you test as much audios as possible so we can improve the normalization? each new error will create a new normalization rule

**Comment by rehandaphedar** [comment]
Sure, I wanna try to create word timings for the complete Qurʾān, so that should be plenty of testing data.

**Comment by rehandaphedar** [comment]
Sorry, I posted the wrong text.txt. This is the correct
[text.txt](https://github.com/user-attachments/files/17093224/text.txt)

**Comment by MahmoudAshraf97** [comment]
I fixed it and some more, please note that this approach is not the correct approach, Quran normalization is not a simple search and replace, it needs more hand-crafted rules that I will not be covering in this repo, so if you want to keep using an Arabic model please handle these rules yourself using the previous two commits as a guide, or use the default model with romanization which will give you better results

**Comment by rehandaphedar** [comment]
Noted.
