### ISSUE TITLE
multiple language support

### ISSUE THREAD

**Issue by JohnHerry** [MahmoudAshraf97/ctc-forced-aligner#37]
Thanks for the job, Is this project support mixed language? like some English word in your mothertone.

**Comment by MahmoudAshraf97** [comment]
it should be yes, just make sure the transcript is romanized correctly because I haven't tested it on a multilingual transcript

**Comment by JohnHerry** [comment]
thank you for the help

**Comment by alinawaz1993** [comment]
@MahmoudAshraf97  how we can add a new language or if we want to add sindi or pashto or low resource language?
is there any special requirement like trained a  new  Acoustic‑Model?

**Comment by MahmoudAshraf97** [comment]
If the default model doesn't work for you, you will need to train a new acoustic model
