### ISSUE TITLE
Issue regarding the last segment of the audio

### ISSUE THREAD

**Issue by Youssef-Barakat** [MahmoudAshraf97/ctc-forced-aligner#42]
Hello! Great job on this, but I noticed that if there's silence after the final segment, the end of the last segment gets extended to the final segment of the audio and I have found also putting star_frequency to edges solve this a bit.
any recommendations?

**Comment by MahmoudAshraf97** [comment]
This is a problem with CTC decoding in general

https://pytorch.org/audio/main/tutorials/ctc_forced_alignment_api_tutorial.html#inconsistent-treatment-of-blank-token
