### ISSUE TITLE
How can i know why it fails?

### ISSUE THREAD

**Issue by MonolithFoundation** [MahmoudAshraf97/ctc-forced-aligner#45]
In my case, I want using ctc to found the missing words, which means, the text might lack words, is there a way to found it (don
t need to know which word, but knows somewhere can not be aligned.

thanks very much if any suggestions

**Comment by MahmoudAshraf97** [comment]
It can do the opposite, detect words in the transcript that might not be in the audio, but finding missing words is difficult as this means you are transcriping the audio again
