### ISSUE TITLE
instructions on training model

### ISSUE THREAD

**Issue by eschmidbauer** [MahmoudAshraf97/ctc-forced-aligner#7]
Hello, thank you for sharing this project. 
I'm wondering if it's possible to fine-tune or train a model? If so, can you share some details on how?
Thanks!

**Comment by MahmoudAshraf97** [comment]
Hello, this project is mainly focused on inference, training is possible using HF transformers, but AFAIK, there's no special training for forced alignment, models for ASR are used directly

**Comment by eschmidbauer** [comment]
thanks! I'm curious about fine-tuning because I noticed the alignment gets completely inaccurate on longer audio clips.

**Comment by eschmidbauer** [comment]
thanks for the assistance here!
