### ISSUE TITLE
Subtitles start at previous word's ending time thus leaving no space in between

### ISSUE THREAD

**Issue by ankitgurua** [MahmoudAshraf97/ctc-forced-aligner#9]
This is aweful when creating subtitles that have few pauses between them as it will show that next subtitle during entire pausing time.

**Comment by MahmoudAshraf97** [comment]
can you upload a file to test with?

**Comment by ankitgurua** [comment]
You can test this on any subtitle file. All models are doing this in all subs

**Comment by MahmoudAshraf97** [comment]
I didn't face this issue so so steps to reproduce would be helpful,
you might try changing `--star_frequency` to `segment` and see if that helps

**Comment by MahmoudAshraf97** [comment]
Hi Henrik, It's a known issue with CTC models that they can't differentiate between repetitions, and silence unless separated by a special token which is `<star>` in this case, check [This](https://pytorch.org/audio/main/tutorials/ctc_forced_alignment_api_tutorial.html#inconsistent-treatment-of-blank-token) for a more detailed explanation.
So usage  completely depends on your use case and whether you care about sentence boundary timestamps or individual words timestamps
